# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.grafica = PlotWidget(self.centralwidget)
        self.grafica.setGeometry(QtCore.QRect(210, 70, 971, 281))
        self.grafica.setObjectName("grafica")
        self.listat = QtWidgets.QListWidget(self.centralwidget)
        self.listat.setGeometry(QtCore.QRect(1250, 70, 111, 281))
        self.listat.setObjectName("listat")
        self.grafica_2 = PlotWidget(self.centralwidget)
        self.grafica_2.setGeometry(QtCore.QRect(210, 401, 971, 281))
        self.grafica_2.setObjectName("grafica_2")
        self.grafica_3 = PlotWidget(self.centralwidget)
        self.grafica_3.setGeometry(QtCore.QRect(210, 743, 971, 280))
        self.grafica_3.setObjectName("grafica_3")
        self.listah = QtWidgets.QListWidget(self.centralwidget)
        self.listah.setGeometry(QtCore.QRect(1250, 400, 111, 281))
        self.listah.setObjectName("listah")
        self.listatp = QtWidgets.QListWidget(self.centralwidget)
        self.listatp.setGeometry(QtCore.QRect(1250, 740, 111, 281))
        self.listatp.setObjectName("listatp")
        self.labelt = QtWidgets.QLabel(self.centralwidget)
        self.labelt.setGeometry(QtCore.QRect(209, 19, 301, 50))
        font = QtGui.QFont()
        font.setFamily("Tempus Sans ITC")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.labelt.setFont(font)
        self.labelt.setScaledContents(False)
        self.labelt.setObjectName("labelt")
        self.labelt_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelt_2.setGeometry(QtCore.QRect(210, 357, 301, 50))
        font = QtGui.QFont()
        font.setFamily("Tempus Sans ITC")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.labelt_2.setFont(font)
        self.labelt_2.setScaledContents(False)
        self.labelt_2.setObjectName("labelt_2")
        self.labelt_3 = QtWidgets.QLabel(self.centralwidget)
        self.labelt_3.setGeometry(QtCore.QRect(210, 697, 301, 50))
        font = QtGui.QFont()
        font.setFamily("Tempus Sans ITC")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.labelt_3.setFont(font)
        self.labelt_3.setScaledContents(False)
        self.labelt_3.setObjectName("labelt_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1255, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1250, 370, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1250, 700, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lcdNumbert = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumbert.setGeometry(QtCore.QRect(1510, 170, 171, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lcdNumbert.setPalette(palette)
        self.lcdNumbert.setObjectName("lcdNumbert")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1510, 130, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lcdNumberth = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumberth.setGeometry(QtCore.QRect(1510, 480, 171, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lcdNumberth.setPalette(palette)
        self.lcdNumberth.setObjectName("lcdNumberth")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1510, 440, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lcdNumbertp = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumbertp.setGeometry(QtCore.QRect(1510, 850, 171, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lcdNumbertp.setPalette(palette)
        self.lcdNumbertp.setObjectName("lcdNumbertp")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1510, 810, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelt.setText(_translate("MainWindow", "Temperatura"))
        self.labelt_2.setText(_translate("MainWindow", "Humedad"))
        self.labelt_3.setText(_translate("MainWindow", "Preción"))
        self.label.setText(_translate("MainWindow", "Valores (°C)"))
        self.label_2.setText(_translate("MainWindow", "Valores (%)"))
        self.label_3.setText(_translate("MainWindow", "Valores (Pa)"))
        self.label_4.setText(_translate("MainWindow", "Último valor:"))
        self.label_5.setText(_translate("MainWindow", "Último valor:"))
        self.label_6.setText(_translate("MainWindow", "Último valor:"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
